### ISSUE TITLE
Missing iOS Icons and Splashscreens

### ISSUE THREAD

**Issue by hdramos** [Microsoft/cordova-docs#10]
Known Issues - CTP 3/3.1 for Visual Studio 2013

The suggested fix for the issue Missing iOS Icons and Splashscreens works. However, the element is removed when editing confix.xml from the designer. Is there any way to get around it besides using an older version of vs-mda-remote?

**Comment by Chuxel** [comment]
Those are the two methods available. These issues are resolved in Visual Studio 2015.
