### ISSUE TITLE
Need to restart VS after setting environment variable for Could Not Create Java Virtual Machine Error

### ISSUE THREAD

**Issue by arangas** [Microsoft/cordova-docs#12]
I ran into [this Android Java](https://github.com/Microsoft/cordova-docs/tree/master/tips-and-workarounds/android#couldnotcreatevm) issue. It is missing the info that Visual Studio needs to be restarted after the environment variable has been set.

It might also be a good idea to reproduce a version of the instructions there and give credit to the source site, just in case that link breaks.

**Comment by Chuxel** [comment]
Thanks for the suggestion. Updated with those details.
