### ISSUE TITLE
Remove duplicate content from repo

### ISSUE THREAD

**Issue by jmatthiesen** [Microsoft/cordova-docs#138]
After a recent folder structure change, we now have articles located in an /articles folder, however we still have those same articles in their pre-existing locations at the root of the repo. This results in duplicate content in the repo and leads to difficulty in understanding where to submit changes. For example, this page:

`package-and-publish/get-your-app-approved.md`

and

`articles/package-and-publish/get-your-app-approved.md`

Have the same content. There should be just one source of truth (in the articles folder, I assume). So that links to the old file locations continue to work, we need to keep files there. I suggest that we replace their content with some simple text like "This document has moved! See it in its new home at: ..." and a link to the new file location.

**Comment by ljzhong** [comment]
The package-and-publish/get-your-app-approved.md indicates that it is depreciated. The only reason that these 'duplicates' exist is so that wild links to the github site will still direct to *a* file, just not the newest one.

**Comment by jmatthiesen** [comment]
Good point. I'd suggest that we instead remove the duplicate content from these files and customize the "deprecated" note so that it has a link to the new location. In the web dev world I'd have this actually perform an HTTP redirect, but we can't do that with GitHub, so this is the next best thing.

One reason to remove the duplicate content: it hurts our search engine results if the same content is indexed in two files. Also, someone may click a link to the old location and likely ignore the deprecated header - then that viewer is reading old docs.

**Comment by jmatthiesen** [comment]
Looks like this is done, thanks!
