### ISSUE TITLE
Cannot open a cordova project that was created using VS2013 Update 4 into Visual Studio 2015 Community Edition

### ISSUE THREAD

**Issue by pantonis** [Microsoft/cordova-docs#14]
Hi,

Cannot open a cordova project that was created using VS2013 Update 4 into Visual Studio 2015 Community Edition.
I get "his project is incompatible with the current edition of Visual Studio".

Any suggestions or workaround?

**Comment by Chuxel** [comment]
See the first item under 
https://github.com/Microsoft/cordova-docs/blob/master/known-issues/known-issues-vs2015.md
