### ISSUE TITLE
Build fail in VS 2015 community  due to the mysql?

### ISSUE THREAD

**Issue by zeusro** [Microsoft/cordova-docs#18]
I just installed the  VS 2015 community version and created a JavaScript-apache cordova project.

It worked once,but after I reopen the project ,It told me that build success but debug fail.

![image](https://cloud.githubusercontent.com/assets/5803609/8999749/69381014-3771-11e5-947e-3d9b8facec23.png)

I really have no idea.

**Comment by zeusro** [comment]
when I ignore the build fail failure message,It will say 
![image](https://cloud.githubusercontent.com/assets/5803609/8999828/30c7a162-3772-11e5-8fae-3a7e1100d532.png)

which means unable to start the adb.Unsupported operation,unknown error.

**Comment by jmatthiesen** [comment]
If you haven't already, please post this question on http://www.stackoverflow.com using the visual-studio-cordova tag. We actively watch and answer questions there, while this repository is reserved for documentation-related issues. Thank you!
