### ISSUE TITLE
Push notification Tutorial

### ISSUE THREAD

**Issue by vinceliao** [Microsoft/cordova-docs#183]
The samples on github :(https://github.com/Azure/mobile-services-samples)
 is either using VS2013 or is not using Visual studio at all. 

And the documentation on azure (https://azure.microsoft.com/en-us/documentation/articles/mobile-services-javascript-backend-windows-universal-dotnet-get-started-push/) 
has all the platform except Cordova.

Can the team add a VS2015 version of the push notification sample with tutorial?
I believe this will help a lot of developers like me struggling to make push notification to work.

**Comment by normesta** [comment]
Hi vinceliao - This sample (https://github.com/Azure/mobile-services-samples/tree/master/CordovaNotificationsArticle) was updated this month and should work with VS 2015 and a VS Cordova project. Pls. have a look. If there are issues with that sample, please do post a new issue to that repository as the sample author monitors feedback pretty regularly. Thx!
