### ISSUE TITLE
Are the Tools for Apache Cordova open source? Where to report issues?

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/cordova-docs#23]
The title says it all.

it's so nice to be able to report issues easily over here at GitHub like we can with Microsoft's Node.js tools. I cannot find any information about whether Tools for Apache Cordova are open source or not or where to easily report issues for it.

**Comment by sorskoot** [comment]
You can find more on contributing and filing issues on http://cordova.apache.org/#contribute

**Comment by waynebloss** [comment]
That's the page for Apache Cordova but I'm asking about the source for *Microsoft's Tools for Apache Cordova* that get installed with *Visual Studio 2015*.

There is nothing about Microsoft Tools for Apache Cordova on that page.

**Comment by Chuxel** [comment]
Tools for Apache Cordova itself is not currently open source. As a result, currently obvious VS product issues are should be reported via the in-IDE ["send a smile/send a frown" feature](https://msdn.microsoft.com/en-us/library/mt280277.aspx?f=255&MSPPError=-2147217396).  General question, implementation help, and other issues should be reported on stackoverflow using the [visual-studio-cordova tag](http://stackoverflow.com/questions/tagged/visual-studio-cordova) as a result. 

As always, the more detail you can provide to reproduce the issue the better.

**Comment by waynebloss** [comment]
Thanks!
