### ISSUE TITLE
Can't Create nor Open Apache Cordova Projects

### ISSUE THREAD

**Issue by fals** [Microsoft/cordova-docs#26]
When I try to open or Create a new Apache Cordova Project the IDE just stop to respond. I found inside the *ActivityLog.xml* some errors related to **Apache Cordova Extension** Initialization:

>8757-4084-8526-E8A1D165433D}  VisualStudio 2015/08/17 13:40:36.261 
>728  Begin package load [ApacheCordovaToolsPackage] {317A330D-8757-4084-8526->E8A1D165433D}  VisualStudio 2015/08/17 13:40:36.261 
>729 ERROR SetSite failed for package [ApacheCordovaToolsPackage] {317A330D-8757-4084-8526->E8A1D165433D} 80131604 VisualStudio 2015/08/17 13:40:36.498 
>730 ERROR End package load [ApacheCordovaToolsPackage] {317A330D-8757-4084-8526->E8A1D165433D} 80131604 VisualStudio 2015/08/17 13:40:36.503 
>731  Entering function CVsPackageInfo::HrInstantiatePackage {317A330D-8757-4084-8526->E8A1D165433D}  VisualStudio 2015/08/17 13:40:48.902 
>732  Begin package load [ApacheCordovaToolsPackage] {317A330D-8757-4084-8526->E8A1D165433D}  VisualStudio 2015/08/17 13:40:48.902 
>733 ERROR SetSite failed for package [ApacheCordovaToolsPackage] {317A330D-8757-4084-8526->E8A1D165433D} 80131604 VisualStudio 2015/08/17 13:40:48.903 
>734 ERROR End package load [ApacheCordovaToolsPackage] 

I had a clean instalation, and just upgraded the VS 2015 Azure SDK, nothing else more, but somehow stop working.

**Comment by jmatthiesen** [comment]
I'm sorry you ran into an issue here, perhaps the following post helps resolve this?

http://stackoverflow.com/questions/31741405/error-setsite-failed-for-package-apachecordovatoolspackage

If you still have issues, please post them to http://stackoverflow.com using the visual-studio-cordova tag. We actively watch and answer questions there, while this repository is focused on Cordova-related documentation.
