### ISSUE TITLE
5.4.0

### ISSUE THREAD

**Issue by rolandoldengarm** [Microsoft/cordova-docs#308]
Build a 5.4.0 project for Windows 10 (UWP x64) results in:

MakeAppx : error : Error info: error C00CE015: App manifest validation error: The app manifest must be valid as per schema: Line 25, Column 203, Reason: The attribute 'ToastCapable' on the element '{http://schemas.microsoft.com/appx/manifest/uap/windows10}VisualElements' is not defined in the DTD/Schema. [C:\demoprojects\BlankCordovaApp1\platforms\windows\CordovaApp.Windows10.jsproj]

**Comment by smatthews1999** [comment]
I get this error as soon as I add plugin "phonegap-plugin-push".

**Comment by rolandoldengarm** [comment]
Still not fixed??!! Just installed latest updates for Visual Studio, including Cordova CLI 5.4.1

Our app is working without any major issues on Android and iOS. But it's so hard to get it working on WP. WP8.1 is too strict (e.g. no network API calls, and JS protection so jQuery and Angular don't work properly).

**Comment by rakatyal** [comment]
Which cordova-windows version are you using? This is caused as Windows 10 removed the toast capable attribute setting and was fixed in the latest release. Upgrading to windows 4.3.0 should remove this issue.

**Comment by rolandoldengarm** [comment]
How can I verify this @rakatyal ? I've installed Cordova via the Visual Studio 2015 installation. Installed the most recent updates this week.
When I run cordova -v, I see 5.4.1?

**Comment by rakatyal** [comment]
Try: cordova platform version windows

**Comment by rolandoldengarm** [comment]
4.1.0... But how can I upgrade this version? cordova platform update windows does not update to 4.3.0?

**Comment by rakatyal** [comment]
cordova platform update windows@4.3.0

**Comment by rakatyal** [comment]
Refer to [this](http://cordova.apache.org/announcements/2016/01/18/cordova-windows-4.3.0.html) for more details.

**Comment by rolandoldengarm** [comment]
Thanks, that has fixed the packaging issue. After running update@4.3.0 I got an error though, caused probably by the barcode-scanner-plugin. See errow below. If I'd try to build, I'd get an error during reinstalling the plugin.
I've reverted to 4.1.0, uninstalled the plugin, then installed 4.3.0, and now it seems to work.

The error with the barcode-scanner-plugin:

````
$ cordova platform update windows@4.3.0
Updating windows project...
Creating Cordova Windows Project:
        App Name  : AppName
        Namespace : ourapp.company.mobile
        Path      : C:\Projects\PhoneApp\platforms\windows
Error: Uh oh!
EISDIR: illegal operation on a directory, read
````

**Comment by rakatyal** [comment]
Great.
