### ISSUE TITLE
Hosted app tutorial does not work properly

### ISSUE THREAD

**Issue by vas85** [Microsoft/cordova-docs#343]
When I use the latest update and Cordova 5.4.1 and the hosted app tutorial:
http://taco.visualstudio.com/en-us/docs/create-a-hosted-app/

I get the following error:
"APPHOST9624: The app can’t use script to load the https://cordovahostedweb-starter.azurewebsites.net/ url because the url launches another app. Only direct user interaction can launch another app."

The error is triggered by this line:
window.location.replace(targetUrl);

The allow-navigation tag is set to the following in config.xml and the CSP is set the same as in the tutorial
<allow-navigation href="https://cordovahostedweb-starter.azurewebsites.net/" />

Can you please have a look? This seems like a severe issue

**Comment by vas85** [comment]
Tag @Mikejo5000 @kirupa

**Comment by Mikejo5000** [comment]
Hi Vas,
I'll take a look. Do you get this error on targeting Windows? What OS? See this error on any other targets? On Windows 10, please verify that you have "Windows 10.0" selected in config.xml, Windows tab (Windows target version). Win81 is not supported in this sample...

**Comment by vas85** [comment]
Ah. I think that might be my problem. When I select Windows 10.0 I get an error about the UWP platform version being too old. Does that get fixed if I update VS?

Thanks for your help

**Comment by Mikejo5000** [comment]
That should get fixed on the VS update; when you start the update, check the optional features to install and make sure that "Universal Windows App Develoment Tools" is selected. It should get selected automatically when you choose to install Cross-plat Mobile Development/ "HTML/JavaScript (Apache Cordova) Update 5", but I'd just make sure about it.

**Comment by vas85** [comment]
Verified updating to the latest version of VS and selecting "Windows 10.0" in config.xml fixed it.

Thanks!
