### ISSUE TITLE
Suggestion for "Build errors caused by long path and file names"

### ISSUE THREAD

**Issue by arangas** [Microsoft/cordova-docs#7]
I recently hit [this issue](https://github.com/Microsoft/cordova-docs/blob/master/tips-and-workarounds/general/README.md#build-errors-long-path) and was able to partially resolve it by following the suggestion of moving the project closer to the root of the drive. However the `npm-cache` folder was still an issue as it lives by default in `C:\Users\username\AppData\Roaming\npm-cache`.

I was able to get around this by creating a `.npmrc` file in my project and specifying a folder that lives in my project (excluded with `.gitignore`). Another option is to move it for the user profile or possibly the entire machine.

I'd be happy to write something up for this if it is useful and a particular approach is preferred!

**Comment by Chuxel** [comment]
Thanks for the suggestion!  Added to the docs.
